# Generated by Django 5.0.6 on 2024-07-23 05:28

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix='', primary_key=True, serialize=False),
        ),
    ]
