# Generated by Django 5.0.6 on 2024-07-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_identifier_alter_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(default='a', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
