# Generated by Django 5.0.6 on 2024-07-23 13:23

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=15, prefix='', primary_key=True, serialize=False),
        ),
    ]
