# Generated by Django 5.0.6 on 2024-06-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='street_1',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='street_2',
        ),
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='addresses.address'),
        ),
    ]
