# Generated by Django 5.0.6 on 2024-06-24 08:19

import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_remove_shelter_city_remove_shelter_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=shelters.models.upload_to),
        ),
    ]
