# Generated by Django 5.0.6 on 2024-06-24 17:07

import django.db.models.deletion
import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_shelter_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shelters.models.upload_to)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shelters.shelter')),
            ],
        ),
    ]
