# Generated by Django 5.0.6 on 2024-06-25 04:57

import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_shelterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterimage',
            name='image',
            field=models.ImageField(upload_to=shelters.models.upload_images),
        ),
    ]
