# Generated by Django 5.0.6 on 2024-07-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
