# Generated by Django 5.0.6 on 2024-06-02 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
