# Generated by Django 5.0.6 on 2024-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
