# Generated by Django 5.0.6 on 2024-07-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_postcode_alter_address_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='address',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
