# Generated by Django 5.0.6 on 2024-06-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stduser',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='addresses.address'),
        ),
    ]
