# Generated by Django 5.0.6 on 2024-06-25 04:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_stduser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stduser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
