# Generated by Django 5.0.6 on 2024-07-23 13:23

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_stduser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stduser',
            name='user_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=15, prefix='', primary_key=True, serialize=False),
        ),
    ]
